[package]
name = "jidhom"
version = "0.1.0-alpha.0"
authors = ["zefr0x"]
edition = "2024"
license = "AGPL-3.0-only"
homepage = "https://github.com/zefr0x/jidhom"
repository = "https://github.com/zefr0x/jidhom.git"
