[package]
name = "db"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
log = { workspace = true }
sea-orm = { version = "1.1.13", default-features = false, features = [
	"sqlx-postgres",
	"runtime-tokio-rustls",
	"macros",
	"with-time",
	"with-uuid",
] }
