# This Github workflow will run lints and fmt for rust on push to main or pull request open.

name: lint
permissions:
    contents: read
on:
    push:
        branches:
            - main
        paths:
            - "**/src/**"
            - "**/Cargo.toml"
            - Cargo.lock
            - rustfmt.toml
            - clippy.toml
    pull_request:
        types: [opened, reopened, synchronize, ready_for_review]
        paths:
            - "**/src/**"
            - "**/Cargo.toml"
            - Cargo.lock
            - rustfmt.toml
            - clippy.toml
    workflow_dispatch:

jobs:
    fmt:
        name: rust-fmt
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

            - name: Install Rust Toolchain
              uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # master @ Aug 23, 2025, 4:20 AM GMT+3
              with:
                  toolchain: nightly
                  components: rustfmt

            - name: Cache Build Artifacts
              uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0

            - name: Check Formating
              run: cargo fmt --check

    clippy:
        name: cargo-clippy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0

            - name: Install Rust Toolchain
              uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # master @ Aug 23, 2025, 4:20 AM GMT+3
              with:
                  toolchain: nightly
                  components: clippy

            - name: Cache Build Artifacts
              uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0

            - name: Check Lints
              run: |
                  cargo clippy --workspace --all-features
